import { Head, useForm } from '@inertiajs/react';
import { Check, X } from 'lucide-react';
import AdminLayout from '@/layouts/admin-layout';
import { Button } from '@/components/ui/button';

type Submission = { id: number; document_type: string; original_name: string; created_at: string; investor: { email: string; profile: { investor_type: string; full_name: string; company_name: string | null; phone: string | null; address: string | null; } } };

function KycRow({ submission }: { submission: Submission }) {
    const form = useForm({ review_notes: '' });
    const review = (status: 'approved' | 'rejected') => form.patch(route('admin.investor-kyc.review', submission.id), { data: { status, review_notes: form.data.review_notes }, preserveScroll: true });

    return <tr className="border-t border-zinc-100"><td className="px-6 py-4 align-top"><div className="flex items-center gap-2"><p className="font-bold text-zinc-950">{submission.investor.profile.full_name}</p><span className="rounded-md bg-zinc-100 px-1.5 py-0.5 text-[10px] font-bold uppercase tracking-wider text-zinc-600">{submission.investor.profile.investor_type}</span></div>{submission.investor.profile.company_name && <p className="mt-0.5 text-sm font-medium text-zinc-700">{submission.investor.profile.company_name}</p>}<div className="mt-2 space-y-0.5 text-xs text-zinc-500"><p>{submission.investor.email}</p>{submission.investor.profile.phone && <p>{submission.investor.profile.phone}</p>}{submission.investor.profile.address && <p>{submission.investor.profile.address}</p>}</div></td><td className="px-6 py-4 align-top text-sm text-zinc-600">{submission.document_type.replace('_', ' ')}<p className="mt-1 text-xs text-zinc-500">{submission.original_name}</p><a href={route('admin.investor-kyc.download', submission.id)} className="mt-2 inline-block text-xs font-bold text-[#3A54A5] hover:text-[#2D4182]">Download securely</a></td><td className="px-6 py-4 align-top text-sm text-zinc-600">{new Date(submission.created_at).toLocaleDateString()}</td><td className="px-6 py-4 align-top"><textarea value={form.data.review_notes} onChange={(event) => form.setData('review_notes', event.target.value)} placeholder="Optional review note" className="mb-2 min-h-20 w-full rounded-xl border border-zinc-200 bg-white p-3 text-sm text-zinc-950 placeholder:text-zinc-400 focus:border-[#3A54A5] focus:ring-[#3A54A5]/20" /><div className="flex justify-end gap-2"><Button size="sm" className="rounded-xl bg-[#3A54A5] hover:bg-[#2D4182]" disabled={form.processing} onClick={() => review('approved')}><Check data-icon="inline-start" /> Approve</Button><Button size="sm" variant="outline" className="rounded-xl text-rose-700 hover:bg-rose-50" disabled={form.processing} onClick={() => review('rejected')}><X data-icon="inline-start" /> Reject</Button></div></td></tr>;
}

export default function InvestorKycIndex({ submissions }: { submissions: { data: Submission[] } }) {
    return <AdminLayout><Head title="KYC queue" /><div className="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8"><p className="text-xs font-bold tracking-[0.16em] text-[#3A54A5] uppercase">Compliance</p><h1 className="mt-2 text-3xl font-black tracking-tight text-zinc-950">KYC queue</h1><p className="mt-2 text-sm text-zinc-600">Review submitted identity documents before protected investor access is enabled.</p><div className="mt-7 overflow-hidden rounded-2xl border border-zinc-200 bg-white"><table className="w-full text-left"><thead className="bg-zinc-50 text-xs font-bold tracking-wider text-zinc-500 uppercase"><tr><th className="px-6 py-4">Investor</th><th className="px-6 py-4">Document</th><th className="px-6 py-4">Submitted</th><th className="px-6 py-4 text-right">Decision</th></tr></thead><tbody>{submissions.data.map((submission) => <KycRow key={submission.id} submission={submission} />)}</tbody></table>{submissions.data.length === 0 && <p className="p-12 text-center text-sm text-zinc-500">No KYC documents await review.</p>}</div></div></AdminLayout>;
}
