import { Head, router } from '@inertiajs/react';
import { Bell, CheckCheck } from 'lucide-react';

type Notification = { id: string; type: string; data: { type?: string; title?: string; body?: string; destination_url?: string | null }; read_at: string | null; created_at: string };
type Paginated<T> = { data: T[] };

export default function NotificationsIndex({ notifications, read_all_url: readAllUrl, read_url_template: readUrlTemplate }: { notifications: Paginated<Notification>; read_all_url: string; read_url_template: string }) {
    const unread = notifications.data.filter((notification) => !notification.read_at).length;
    return <main className="min-h-screen bg-[#f4f7ff] px-6 py-10 text-zinc-950 sm:px-10"><Head title="Notifications" />
        <div className="mx-auto max-w-4xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold tracking-[0.16em] text-[#3A54A5] uppercase">Platform alerts</p><h1 className="mt-2 text-3xl font-black tracking-tight">Notifications</h1><p className="mt-2 text-sm text-zinc-600">{unread ? `${unread} unread alert${unread === 1 ? '' : 's'}` : 'You are all caught up.'}</p></div>{unread > 0 && <button onClick={() => router.patch(readAllUrl)} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-zinc-200 bg-white px-4 text-sm font-bold text-zinc-700 hover:bg-zinc-50"><CheckCheck className="size-4" />Mark all read</button>}</div>
        <div className="mt-8 overflow-hidden rounded-2xl border border-white/80 bg-white shadow-[0_16px_36px_rgba(33,56,120,0.06)]">{notifications.data.length === 0 ? <div className="px-6 py-16 text-center"><Bell className="mx-auto size-8 text-zinc-300" /><p className="mt-4 font-bold">No notifications yet.</p></div> : notifications.data.map((notification) => <button key={notification.id} onClick={() => !notification.read_at && router.patch(readUrlTemplate.replace('__notification__', notification.id))} className={`flex w-full items-start gap-4 border-b border-zinc-100 px-6 py-5 text-left last:border-0 ${notification.read_at ? 'bg-white' : 'bg-[#eef2ff]/45'}`}><span className="mt-1 size-2 shrink-0 rounded-full bg-[#3A54A5] opacity-80" /><span><span className="block text-sm font-bold text-zinc-900">{notification.data.title ?? notification.data.type?.replaceAll('_', ' ') ?? 'Platform update'}</span>{notification.data.body && <span className="mt-1 block text-sm text-zinc-600">{notification.data.body}</span>}<span className="mt-1 block text-xs text-zinc-500">{new Date(notification.created_at).toLocaleString()}</span></span></button>)}</div></div></main>;
}
