import { Head, router } from '@inertiajs/react';
import { Eye, EyeOff, FileCheck2 } from 'lucide-react';
import AdminLayout from '@/layouts/admin-layout';
import { Button } from '@/components/ui/button';

type Profile = { id: number; company_name: string | null; sector: string | null; overall_score: number | null; spotlight_one_liner: string; has_reviewed_pitch_deck: boolean; is_published: boolean; verified_badges_count: number };

export default function SpotlightIndex({ profiles }: { profiles: Profile[] }) {
    const update = (profile: Profile, publish: boolean) => router.patch(route('admin.spotlight.update', profile.id), { publish }, { preserveScroll: true });

    return <AdminLayout><Head title="Spotlight management" /><div className="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8"><div className="flex flex-col justify-between gap-4 border-b border-zinc-200 pb-6 sm:flex-row sm:items-end"><div><p className="text-xs font-bold tracking-[0.16em] text-[#3A54A5] uppercase">Dealflow</p><h1 className="mt-2 text-3xl font-black tracking-tight text-zinc-950">Spotlight management</h1><p className="mt-2 text-sm text-zinc-600">Publish only PARAGON-complete startups with reviewed investor materials.</p></div><p className="text-sm font-semibold text-zinc-500">{profiles.filter((profile) => profile.is_published).length} currently published</p></div><div className="mt-7 overflow-hidden rounded-2xl border border-zinc-200 bg-white shadow-[0_16px_36px_rgba(33,56,120,0.06)]"><table className="w-full min-w-[780px] text-left"><thead className="bg-zinc-50 text-xs font-bold tracking-wider text-zinc-500 uppercase"><tr><th className="px-6 py-4">Startup</th><th className="px-6 py-4">Readiness</th><th className="px-6 py-4">Pitch deck</th><th className="px-6 py-4">Status</th><th className="px-6 py-4 text-right">Action</th></tr></thead><tbody>{profiles.map((profile) => <tr key={profile.id} className="border-t border-zinc-100"><td className="px-6 py-4"><p className="font-bold text-zinc-950">{profile.company_name ?? 'Unnamed startup'}</p><p className="mt-1 max-w-md text-sm text-zinc-600">{profile.spotlight_one_liner}</p></td><td className="px-6 py-4 text-sm text-zinc-600"><p>{profile.sector ?? 'Sector pending'}</p><p className="mt-1 text-xs text-zinc-500">Score {profile.overall_score ?? '—'} · {profile.verified_badges_count} badges</p></td><td className="px-6 py-4"><span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-xs font-bold ${profile.has_reviewed_pitch_deck ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-700'}`}><FileCheck2 className="size-3.5" />{profile.has_reviewed_pitch_deck ? 'Reviewed' : 'Needs review'}</span></td><td className="px-6 py-4"><span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-bold ${profile.is_published ? 'bg-[#3A54A5]/10 text-[#3A54A5]' : 'bg-zinc-100 text-zinc-600'}`}>{profile.is_published ? 'Published' : 'Private'}</span></td><td className="px-6 py-4 text-right"><Button size="sm" variant={profile.is_published ? 'outline' : 'default'} className={profile.is_published ? 'rounded-xl' : 'rounded-xl bg-[#3A54A5] hover:bg-[#2D4182]'} disabled={!profile.is_published && !profile.has_reviewed_pitch_deck} onClick={() => update(profile, !profile.is_published)}>{profile.is_published ? <><EyeOff data-icon="inline-start" /> Unpublish</> : <><Eye data-icon="inline-start" /> Publish</>}</Button></td></tr>)}</tbody></table>{profiles.length === 0 && <p className="p-12 text-center text-sm text-zinc-500">No founder Spotlight profiles are ready for review.</p>}</div></div></AdminLayout>;
}
