import { Head, Link } from '@inertiajs/react';
import { ArrowLeft, BadgeCheck, FileText, LockKeyhole } from 'lucide-react';
import { PinpointLogo } from '@/components/pinpoint-logo';
import { Button } from '@/components/ui/button';

type Entry = { slug: string; company_name: string | null; spotlight_one_liner: string; summary: string; sector: string | null; batch: string | null; overall_score: number | null; verified_badges_count: number; badges: { id: number; label: string; badge_type: string }[]; pitch_deck: { original_filename: string } | null; can_view_pitch_deck: boolean };

export default function SpotlightShow({ entry }: { entry: Entry }) {
    return <main className="min-h-screen bg-[#f4f7ff] text-zinc-950"><Head title={entry.company_name ?? 'Spotlight startup'} /><header className="mx-auto flex max-w-6xl items-center justify-between px-6 py-7"><PinpointLogo height={24} /><Link href={route('investor.spotlight.index')} className="inline-flex items-center gap-2 rounded-xl px-3 py-2 text-sm font-semibold text-zinc-600 hover:bg-white"><ArrowLeft className="size-4" /> Spotlight</Link></header><section className="mx-auto max-w-5xl px-6 py-10 sm:py-14"><div className="rounded-2xl border border-white/80 bg-white p-7 shadow-[0_20px_55px_rgba(33,56,120,0.10)] sm:p-10"><p className="text-xs font-bold tracking-[0.16em] text-[#3A54A5] uppercase">{entry.sector ?? 'PIN Spotlight'}{entry.batch ? ` · ${entry.batch}` : ''}</p><div className="mt-5 flex flex-col justify-between gap-5 sm:flex-row"><div><h1 className="text-4xl font-black tracking-tight">{entry.company_name ?? 'PIN startup'}</h1><p className="mt-4 max-w-3xl text-lg leading-8 text-zinc-600">{entry.spotlight_one_liner}</p></div><span className="h-fit rounded-full bg-[#3A54A5]/10 px-4 py-2 text-sm font-bold text-[#3A54A5]">PARAGON {entry.overall_score ?? '—'}</span></div><div className="mt-9 border-t border-zinc-100 pt-8"><h2 className="text-xl font-extrabold">Company overview</h2><p className="mt-4 max-w-3xl whitespace-pre-line leading-7 text-zinc-600">{entry.summary}</p></div><div className="mt-9 border-t border-zinc-100 pt-8"><h2 className="text-xl font-extrabold">Verified signals</h2><div className="mt-4 flex flex-wrap gap-2">{entry.badges.map((badge) => <span key={badge.id} className="inline-flex items-center gap-1.5 rounded-full bg-zinc-100 px-3 py-1.5 text-xs font-bold text-zinc-700"><BadgeCheck className="size-3.5 text-[#3A54A5]" />{badge.label}</span>)}</div></div></div><div className="mt-7 rounded-2xl border border-[#3A54A5]/12 bg-[#eef2ff] p-6"><div className="flex items-start gap-4"><div className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-white text-[#3A54A5]">{entry.can_view_pitch_deck ? <FileText className="size-5" /> : <LockKeyhole className="size-5" />}</div><div><h2 className="font-extrabold">Pitch deck</h2>{entry.pitch_deck ? <p className="mt-1 text-sm text-zinc-600">{entry.can_view_pitch_deck ? entry.pitch_deck.original_filename : 'Complete KYC approval to access this reviewed pitch deck.'}</p> : <p className="mt-1 text-sm text-zinc-600">A reviewed pitch deck is not available yet.</p>}{entry.pitch_deck && entry.can_view_pitch_deck && <Button asChild className="mt-4 rounded-xl bg-[#3A54A5] hover:bg-[#2D4182]"><a href={route('investor.spotlight.pitch-deck', entry.slug)}>Download pitch deck</a></Button>}</div></div></div></section></main>;
}
