import { Head, Link } from '@inertiajs/react';
import { ArrowRight, ShieldCheck } from 'lucide-react';

import { PinpointLogo } from '@/components/pinpoint-logo';
import SideRays from '@/components/SideRays';
import { Button } from '@/components/ui/button';

interface Props { cta: { label: string; url: string; enabled: boolean } }

export default function Landing({ cta }: Props) {
    return <><Head title="Pinpoint Investment Network" /><main className="relative min-h-screen overflow-hidden bg-[#f4f7ff] text-zinc-950"><div className="pointer-events-none fixed inset-0 opacity-35"><SideRays rayColor1="#3A54A5" rayColor2="#BFDBFE" origin="top-left" speed={1.4} intensity={0.8} spread={2} tilt={0} saturation={1.1} blend={0.24} falloff={2.3} opacity={0.25} /></div><header className="relative z-10 mx-auto flex max-w-6xl items-center justify-between px-6 py-7"><PinpointLogo height={24} /><Link href={route('investor.login')} className="rounded-full px-4 py-2 text-sm font-semibold text-[#3A54A5] hover:bg-white/70">Log in</Link></header><section className="relative z-10 mx-auto grid max-w-6xl items-center gap-10 px-6 py-18 lg:grid-cols-[1.2fr_0.8fr]"><div><p className="text-xs font-bold tracking-[0.16em] text-[#3A54A5] uppercase">Pinpoint Investment Network</p><h1 className="mt-5 max-w-3xl text-5xl font-black tracking-tight sm:text-6xl">Curated dealflow, with diligence already in view.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-zinc-600">PIN gives qualified investors a considered way to discover PARAGON-complete startups, while Pinpoint remains present throughout the process.</p><div className="mt-9">{cta.enabled ? <Button asChild size="lg" className="rounded-xl bg-[#3A54A5] px-6 font-bold hover:bg-[#2D4182]"><a href={cta.url}>{cta.label}<ArrowRight data-icon="inline-end" /></a></Button> : <p className="text-sm font-semibold text-zinc-500">Investor applications are temporarily unavailable.</p>}</div><p className="mt-7 max-w-xl text-xs leading-5 text-zinc-500">PIN is a curated visibility channel, not a brokerage or investment adviser. Nothing here is an offer of securities or investment advice.</p></div><aside className="rounded-2xl border border-white/80 bg-white p-7 shadow-[0_20px_55px_rgba(33,56,120,0.10)]"><ShieldCheck className="size-9 text-[#3A54A5]" /><h2 className="mt-6 text-2xl font-extrabold">A controlled path to opportunity</h2><ul className="mt-6 flex flex-col gap-5 text-sm leading-6 text-zinc-600"><li><strong className="text-zinc-900">Curated Spotlight:</strong> only completed PARAGON journeys qualify.</li><li><strong className="text-zinc-900">Protected access:</strong> detailed documents stay inside authenticated data rooms.</li><li><strong className="text-zinc-900">Pinpoint oversight:</strong> the platform remains informed at every decision point.</li></ul></aside></section></main></>;
}
